name: todo_with_grab
description: A todo app made using Grab.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  grab: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.8.0
  path_provider: ^2.0.13
  pot: ^0.4.2

dev_dependencies:
  flutter_lints: ^2.0.1
  path: ^1.8.3
  test: ^1.23.1

flutter:
  uses-material-design: true
