name: todo_with_grab
description: A todo app made using Grab.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  grab: ^0.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.7.0
  path_provider: ^2.0.11
  pot: ^0.3.2

dev_dependencies:
  flutter_lints: ^2.0.1
  path: ^1.8.2
  test: ^1.21.4

flutter:
  uses-material-design: true
