name: todo_with_grab
description: A todo app made using Grab.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  grab: ^0.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.9.1
  path_provider: ^2.1.1
  pot: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.3
  path: ^1.8.3
  test: ^1.24.7

  custom_lint: ^0.5.3
  grab_lints: ^0.3.2

flutter:
  uses-material-design: true
