name: todo_with_grab
description: A todo app made using Grab.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  grab: ^1.0.0-dev.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.9.1
  path_provider: ^2.1.2
  pot: ^0.7.1

dev_dependencies:
  flutter_lints: ^3.0.1
  path: ^1.9.0
  test: ^1.25.1

flutter:
  uses-material-design: true
